


### test POST /list with validation failed
POST {{baseUrl}}/list
Content-Type: application/json
{}

> {%
client.test("status=400", function () {
  client.assert(response.status === 400, "status code error")
  client.assert(JSON.stringify(response.body) == JSON.stringify({
    data: {
      validation: {
        name: [
          "Name can't be blank"
        ]
      }
    },
    message: "required fields are missing",
    status: "bad request"
  }))
})
%}


### test POST /list
POST {{baseUrl}}/list
Content-Type: application/json
{
  "name": "test"
}

> {%
client.test("status=201", function () {
  client.assert(response.status === 201, "status code error")
  client.global.set("listId", response.body.data.listId)
})
%}

HTTP/1.1 400  - Bad Request
access-control-allow-credentials: true
content-type: application/json; charset=utf-8
vary: origin
access-control-expose-headers: WWW-Authenticate,Server-Authorization
cache-control: no-cache
content-length: 119
date: Sat, 09 Jul 2022 04:44:04 GMT
connection: close


### test GET /list
GET {{baseUrl}}/list?listId={{listId}}
> {%
client.test("status=200", function () {
  client.assert(response.status === 200, "status code error")
})
%}


### test PUT /list
PUT {{baseUrl}}/list
Content-Type: application/json
{"name":"test-update","listId":"{{listId}}"}

> {%
client.test("status=200", function() {
  client.assert(response.status === 200, "status code error")
})
%}




### test POST /task
POST {{baseUrl}}/task
{
  "listId":"{{listId}}",
  "description":"test-description",
  "completed":false
}

> {%
client.test("status=201", function () {
  client.assert(response.status === 201, "status code error")
  client.global.set("taskId", response.body.data.taskId)
})
 %}




### test GET /task
GET {{baseUrl}}/task?listId={{listId}}&taskId={{taskId}}
> {%
client.test("status=200", function () {
  client.assert(response.status === 200, "status code error")
})
 %}


### test PUT /task
PUT {{baseUrl}}/task
{
  "listId":"{{listId}}",
  "taskId":"{{taskId}}",
  "description": "updated task",
  "completed": true
}

> {%
client.test("status=200", function () {
  client.assert(response.status === 200, "status code error")
})
 %}




### test DELETE /task
DELETE {{baseUrl}}/task?listId={{listId}}&taskId={{taskId}}
{
  "listId":"{{listId}}",
  "taskId":"{{taskId}}"
}

> {%
client.test("status=204", function () {
  client.assert(response.status === 204, "status code error")
})
 %}




### test DELETE /list
DELETE {{baseUrl}}/list?listId={{listId}}
> {%
client.test("status=204", function () {
  client.assert(response.status === 204, "status code error")
})
%}